# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-10 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_choreo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('length', models.FloatField()),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music_choreo_app.Release')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=set([('number', 'release')]),
        ),
    ]
