# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-10 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_choreo_app', '0003_auto_20171210_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='number',
            field=models.PositiveSmallIntegerField(verbose_name='release number'),
        ),
        migrations.AlterField(
            model_name='track',
            name='number',
            field=models.PositiveSmallIntegerField(verbose_name='track number'),
        ),
    ]
